# Generated by Django 3.2.3 on 2021-06-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('children', models.ManyToManyField(related_name='_forum_message_children_+', to='forum.Message')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.message')),
            ],
        ),
    ]
