# Generated by Django 3.2.3 on 2021-06-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='children',
        ),
        migrations.RemoveField(
            model_name='message',
            name='parent',
        ),
        migrations.AddField(
            model_name='message',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='_forum_message_answers_+', to='forum.Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='root_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.post'),
        ),
    ]
