# Generated by Django 3.2.3 on 2021-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210611_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author_ip',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=15),
        ),
        migrations.AddField(
            model_name='message',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='author_ip',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
