# Generated by Django 3.2.3 on 2021-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210611_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='author_ip',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_ip',
        ),
        migrations.AlterField(
            model_name='message',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
