# Generated by Django 3.2.3 on 2021-06-11 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210611_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='root_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='forum.message'),
        ),
    ]
